# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/panyue/code/my_github/HUST-DataStructure-Labs

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/panyue/code/my_github/HUST-DataStructure-Labs

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panyue/code/my_github/HUST-DataStructure-Labs/CMakeFiles /home/panyue/code/my_github/HUST-DataStructure-Labs/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/panyue/code/my_github/HUST-DataStructure-Labs/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named linearlist

# Build rule for target.
linearlist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linearlist
.PHONY : linearlist

# fast build rule for target.
linearlist/fast:
	$(MAKE) -f CMakeFiles/linearlist.dir/build.make CMakeFiles/linearlist.dir/build
.PHONY : linearlist/fast

#=============================================================================
# Target rules for targets named wsserver

# Build rule for target.
wsserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wsserver
.PHONY : wsserver

# fast build rule for target.
wsserver/fast:
	$(MAKE) -f CMakeFiles/wsserver.dir/build.make CMakeFiles/wsserver.dir/build
.PHONY : wsserver/fast

lab01/my_linearlist.o: lab01/my_linearlist.c.o

.PHONY : lab01/my_linearlist.o

# target to build an object file
lab01/my_linearlist.c.o:
	$(MAKE) -f CMakeFiles/linearlist.dir/build.make CMakeFiles/linearlist.dir/lab01/my_linearlist.c.o
.PHONY : lab01/my_linearlist.c.o

lab01/my_linearlist.i: lab01/my_linearlist.c.i

.PHONY : lab01/my_linearlist.i

# target to preprocess a source file
lab01/my_linearlist.c.i:
	$(MAKE) -f CMakeFiles/linearlist.dir/build.make CMakeFiles/linearlist.dir/lab01/my_linearlist.c.i
.PHONY : lab01/my_linearlist.c.i

lab01/my_linearlist.s: lab01/my_linearlist.c.s

.PHONY : lab01/my_linearlist.s

# target to generate assembly for a file
lab01/my_linearlist.c.s:
	$(MAKE) -f CMakeFiles/linearlist.dir/build.make CMakeFiles/linearlist.dir/lab01/my_linearlist.c.s
.PHONY : lab01/my_linearlist.c.s

server/wsserver.o: server/wsserver.c.o

.PHONY : server/wsserver.o

# target to build an object file
server/wsserver.c.o:
	$(MAKE) -f CMakeFiles/wsserver.dir/build.make CMakeFiles/wsserver.dir/server/wsserver.c.o
.PHONY : server/wsserver.c.o

server/wsserver.i: server/wsserver.c.i

.PHONY : server/wsserver.i

# target to preprocess a source file
server/wsserver.c.i:
	$(MAKE) -f CMakeFiles/wsserver.dir/build.make CMakeFiles/wsserver.dir/server/wsserver.c.i
.PHONY : server/wsserver.c.i

server/wsserver.s: server/wsserver.c.s

.PHONY : server/wsserver.s

# target to generate assembly for a file
server/wsserver.c.s:
	$(MAKE) -f CMakeFiles/wsserver.dir/build.make CMakeFiles/wsserver.dir/server/wsserver.c.s
.PHONY : server/wsserver.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... linearlist"
	@echo "... wsserver"
	@echo "... lab01/my_linearlist.o"
	@echo "... lab01/my_linearlist.i"
	@echo "... lab01/my_linearlist.s"
	@echo "... server/wsserver.o"
	@echo "... server/wsserver.i"
	@echo "... server/wsserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

